// /app/cars/page.tsx

"use client"; 

import { useState, useEffect } from 'react'; 
import Link from 'next/link';
import { Car, ArrowLeft, BrainCircuit } from 'lucide-react'; 
import Modal from '../components/Modal';



// Define a type for our car data for type safety
type CarValuation = {
  id: string;
  brand: string;
  model: string;
  year: number;
  mileage: number;
  enpower: number;
  envolume: number;
  fuel_type: string;
  transmission: string;
  estimatedPrice: number;
  imageUrl: string;
  createdAt: string;
};


export default function CarsPage() {
  const [cars, setCars] = useState<CarValuation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalContent, setModalContent] = useState<React.ReactNode>(null);
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);

  useEffect(() => {
    // Fetch data on component mount
    async function fetchData() {
      try {
        const response = await fetch('/api/cars'); 
        if (!response.ok) throw new Error("Failed to fetch cars");
        const data = await response.json();
        setCars(data.items);
      } catch (error) {
        console.error(error);
      } finally {
        setIsLoading(false);
      }
    }
    fetchData();
  }, []);
  
  // Function to handle the AI summary button click
  const handleSummaryClick = async (car: CarValuation) => {
    setIsModalOpen(true);
    setIsGeneratingSummary(true);
    
    // Show loading state
    setModalContent(
      <div>
        <h3 className="text-xl font-bold text-gray-800 flex items-center">
            <BrainCircuit className="mr-2 text-indigo-600 animate-pulse" />
            AI Summary for {car.brand} {car.model}
        </h3>
        <div className="mt-4 flex items-center justify-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
          <p className="ml-3 text-gray-600">Generating AI summary...</p>
        </div>
      </div>
    );

    try {
      // Call the AI summary API
      const response = await fetch('/api/ai-summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          brand: car.brand,
          model: car.model,
          year: car.year,
          mileage: car.mileage,
          enpower: car.enpower,
          envolume: car.envolume,
          fuel_type: car.fuel_type,
          transmission: car.transmission,
          estimatedPrice: car.estimatedPrice,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate summary');
      }

      // Display the AI-generated summary
      setModalContent(
        <div>
          <h3 className="text-xl font-bold text-gray-800 flex items-center">
              <BrainCircuit className="mr-2 text-indigo-600" />
              AI Summary for {car.brand} {car.model}
          </h3>
          <div className="mt-4 text-gray-700 leading-relaxed">
            {data.summary}
          </div>
          <div className="mt-4 pt-4 border-t border-gray-200">
            <p className="text-xs text-gray-500 flex items-center">
              <span className="mr-2">🤖</span>
              Generated by Azure OpenAI ({data.model})
            </p>
          </div>
        </div>
      );
    } catch (error: any) {
      console.error('Error fetching AI summary:', error);
      
      // Display error message
      setModalContent(
        <div>
          <h3 className="text-xl font-bold text-gray-800 flex items-center">
              <BrainCircuit className="mr-2 text-red-600" />
              AI Summary for {car.brand} {car.model}
          </h3>
          <div className="mt-4 p-4 bg-red-50 rounded-lg">
            <p className="text-red-800 font-medium">Unable to generate summary</p>
            <p className="mt-2 text-sm text-red-600">
              {error.message || 'Please check your Azure OpenAI configuration and try again.'}
            </p>
          </div>
        </div>
      );
    } finally {
      setIsGeneratingSummary(false);
    }
  };


  return (
    <>
      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)}>
          {modalContent}
      </Modal>

      <div className="min-h-screen bg-gray-100">
        <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-900 flex items-center">
              <Car className="mr-3 h-7 w-7" />
                Stored Car Valuations
            </h1>
             <div className="flex justify-center mb-6">
            <img src="./logo1.JPG" alt="Logo" className="h-16 w-auto" />
          </div>
            <Link href="/" className="inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md shadow-sm text-gray-700 bg-white hover:bg-gray-50 transition-colors">
                <ArrowLeft className="mr-2 h-5 w-5" />
                Back to Estimator
            </Link>
        </div>
      </header>
        <main>
          <div className="max-w-7xl mx-auto py-8 sm:px-6 lg:px-8">
            {isLoading ? <p>Loading cars...</p> : (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                {cars.map((car) => (
                  <div key={car.id} className="bg-white rounded-lg shadow-md overflow-hidden flex flex-col">
                    <img src={car.imageUrl} alt={`${car.brand} ${car.model}`} className="w-full h-48 object-cover" />
                    <div className="p-6 flex flex-col flex-grow">
                            <h2 className="text-xl font-bold text-gray-800">{car.brand} {car.model}</h2>
                              <p className="text-sm text-gray-500 mt-1">{car.year}</p>
                              
                              <div className="mt-4 flex justify-between items-end">
                                  <div className="text-left">
                                      <p className="text-xs text-gray-500">Mileage</p>
                                      <p className="text-md font-semibold text-gray-800">{car.mileage.toLocaleString()} km</p>
                                  </div>
                                  <div className="text-right">
                                      <p className="text-xs text-gray-500">Estimated Price</p>
                                      <p className="text-lg font-bold text-green-600">${car.estimatedPrice.toLocaleString()}</p>
                                  </div>
                              </div>
                      <div className="flex-grow"></div> {/* Pushes button to the bottom */}
                      {/* vvv NEW BUTTON HERE vvv */}
                      <button
                        onClick={() => handleSummaryClick(car)}
                        className="mt-4 w-full inline-flex items-center justify-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 transition-colors"
                      >
                        <BrainCircuit className="mr-2 h-5 w-5 text-indigo-500" />
                        Get AI Summary
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </main>
      </div>
    </>
  );
}